# Generated by Django 3.2.5 on 2021-07-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0002_auto_20210731_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='aleludago@gmail.com', max_length=254, verbose_name='Enter your Email')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='Student Id')),
            ],
        ),
    ]
