# Generated by Django 3.2.5 on 2021-07-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
